projectceladon/device-intel-build

tasks/publish.mk

Change-Id: I4330502bd710a28153e01a79689d847d452dd47d
Tracked-On: OAM-68895
Signed-off-by: sgnanase <sundar.gnanasekaran@intel.com>

[CELADON] Fix Kernel PATH issue

---

tasks/publish.mk

Generate grub installer in publish_ci build
Tracked-On: OAM-85598
Signed-off-by: Meng Xianglin <xianglinx.meng@intel.com>

Add publish_grubinstaller to publish_ci

---

tasks/publish.mk

Tracked-On: OAM-85443
Signed-off-by: Meng Xianglin <xianglinx.meng@intel.com>

Publish GRUB installer only in eng or userdebug build

---

tasks/publish.mk

Tracked-On: OAM-86511
Signed-off-by: Wang, Liang <liang.wang@intel.com>

Add support for building CIC

---

tasks/publish.mk

Tracked-On: OAM-86699
Signed-off-by: Wang, Liang <liang.wang@intel.com>

Fix tab format errror for CIC publish target

---

releasetools/sign_target_files_efis

Tracked-On: OAM-85429
Signed-off-by: Regnier, Philippe <philippe.regnier@intel.com>

Fix resign script

---

releasetools/update_esp.py

Tracked-On: OAM-86715
Signed-off-by: Zhang, GaofengX <gaofengx.zhang@intel.com>

To update esp partition for cic by update_esp.py

---

core/definitions.mk

Add flag: -Wa,--noexecstack
Change-Id: I6cd2c588a631c60036516180aae12b7f87486b46
Tracked-On: OAM-88544
Signed-off-by: JianFeng,Zhou <jianfeng.zhou@intel.com>

disable execstack for kernelflinger

---

tasks/publish.mk

Tracked-On: OAM-88695
Signed-off-by: sgnanase <sundar.gnanasekaran@intel.com>

[CIC] Update publish.mk for CIC

---

create_gpt_image.py
releasetools/bootimg_sig_struct.py
releasetools/flash_cmd_generator.py
releasetools/flashflsxml.py
releasetools/flashxml.py
releasetools/iniparser.py
releasetools/intel_common.py
releasetools/update_esp.py
releasetools/verified_boot_common.py
tasks/checkvendor.py
test/corrupt_bootloader_img.py
test/extract_fastboot.py
test/parse_fec_verity.py
test/parse_rsci_table.py
test/releasetools.py

ConfigParser & unicode need keep Python2 format
Change-Id: Iaa4b26a121d77b2c91145bc446d63286a54f45fe
Tracked-On: OAM-89831
Signed-off-by: Xihua Chen <xihua.chen@intel.com>

Use 2to3 tool to upgrade Python2 scripts

---

core/definitions.mk

Tracked-On: OAM-90311
Signed-off-by: JianFeng,Zhou <jianfeng.zhou@intel.com>

Kernelflinger: add build flags -Werror=format-security -Wa,--noexecstack

---

core/definitions.mk

Tracked-On: OAM-88873
Signed-off-by: JianFeng,Zhou <jianfeng.zhou@intel.com>

Kernelflinger: add build flags -Werror=format-security

---

tasks/platform_rma_tools.mk

since rma tools is not  in release list, skip building it
Tracked-On: OAM-90436
Signed-off-by: JianFeng,Zhou <jianfeng.zhou@intel.com>

skip rma tools build

---

tasks/publish.mk

Zipping the scripts to the pub output in buildbot

---

tasks/publish.mk

Release folder structure is modified , created a tar ball

---

tasks/flashfiles.mk
tasks/publish.mk

Handling the release folder structure in make flashfiles only

---

tasks/flashfiles.mk

Release files are removed for rebuild

---

tasks/flashfiles.mk
tasks/publish.mk

Removing the files to reduce the artifactory upload

---

tasks/flashfiles.mk

Making vertical utils part of the tar ball

---

tasks/flashfiles.mk

Tracked-On: OAM-91960
Signed-off-by: sgnanase <sundar.gnanasekaran@intel.com>

Enable host-pkg PHONY

---

tasks/flashfiles.mk

Tracked-On: OAM-94280
Signed-off-by: swaroopb<swaroop.balan@intel.com>

Adding new test target for development

---

tasks/flashfiles.mk

Change-Id: I3c3bca4f274cce71b71b26e95d131d2724a3013a
Tracked-On: OAM-96589
Signed-off-by: Amalendu Prasad Das <amalendu.prasad.das@intel.com>

Making keybox_provisioning part of the tar ball

---

tasks/flashfiles.mk

target only
Tracked-On: OAM-97063

Generating Release deb files for r2_caas lunch

---

tasks/flashfiles.mk

Replacing the caas.img.gz with flashfiles.zip

---

tasks/flashfiles.mk

ota update from host need use scripts in update_engine
Tracked-On: OAM-97151
Signed-off-by: Xihua Chen <xihua.chen@intel.com>

add update_device scripts & ota.zip into Release_Deb package

---

tasks/flashfiles.mk

available
Tracked-On: OAM-97203

Copy the ota files only if the out/dist is

---

tasks/flashfiles.mk

New Lunch Target caas_var added for PGP

---

tasks/flashfiles.mk

to caas_cfc for PGP
Tracked-On: OAM-97475

Renaming the Lunch Target caas_var

---

tasks/flashfiles.mk

remove unused files in release.deb
Tracked-On: OAM-99498
Signed-off-by: Xihua Chen <xihua.chen@intel.com>

configure release.deb

---

tasks/flashfiles.mk

Tracked-On: OAM-98783
Signed-off-by: Sivaramakrishnan, UdhayanX <udhayanx.sivaramakrishnan@intel.com>

Packaging vertical_prod patches

---

tasks/flashfiles.mk

1. Currently the release build of CIV_R cannot boot up. Apex
files cannot be resigned successfully due to the restriction
of PATH tools. The tool of debugfs cannot be found in the
default PATH variable, need to append SOONG_HOST_OUT to the
PATH for sign_target_files_apks command.
2. There is no release build for the GPT image currently.
However, PGP ships a GPT image in its Release.deb instead
of a flashfiles package. Need to create a release build
for the GPT image from a flashfiles release package.
Signed-off-by: ji, zhenlong z <zhenlong.z.ji@intel.com>

Fix some release build issues

---

tasks/flashfiles.mk

Adding car UI lunch target

---

tasks/flashfiles.mk

Some NUCs don't have build-in UEFI shell, so it is impossible to
install civ image for BM. We make a new installer image which
independence on UEFI shell. The image can be used on both bare
mental and CIV.
Tracked-On: OAM-102690

Make civ as USB disk installer image

---

tasks/flashfiles.mk

1. split >4GB images
2. zip caas-usb-install-{varient}.img and new generate caas-usb-install-{varient}.img.zip

split files and new generate caas-usb-install-{varient}.img.zip

---

tasks/flashfiles.mk

Remove old usb installer zip image before a new zip

---

tasks/flashfiles.mk

remove unwanted file from caas-use

---

core/definitions.mk

Tracked-On: OAM-103426
Signed-off-by: svenate <salini.venate@intel.com>

Update clang library version

---

tasks/flashfiles.mk

Also fix issue about Total number of sectors not a
multiple of sectors per track (63)
Tracked-On: OAM-103711

put flashfile iso zip file to public

---

tasks/flashfiles.mk

Support build celadon images as ISO format. The image is ISO format bootable image which can be burned to a bootable CD/DVD or clone to USB pendrive. The image can be flashed to CIV and BM. It is independence on UEFI Shell.
Tracked-On: OAM-103805

Make celadon as ISO file format image

---

tasks/flashfiles.mk

Change ISO build target from civ_iso to iso

---

tasks/flashfiles.mk

1. system.img vendor.img and product.img are covered by super.img, remove them to reduce image size
2. iso images will be generate while executing "make flashfiles"
Tracked-On: OAM-104014

Remove unnecessary images from flashfiles.zip and generate iso format image in flashfiles build target

---

LICENSE

Update License file for device-intel-build

---

tasks/flashfiles.mk

Release deb is added for caas for customer

---

tasks/flashfiles.mk

Modifying the path since we removed caas_dev

---

.github/workflows/Runchecks.yaml

Added support for TriggerBuild

Modify github workflow to support TriggerBuild

---

tasks/flashfiles.mk

Adding new Lunch target for Development Purpose

---

core/definitions.mk

Build ACRN hypervisor as container format image required by Slim Bootloader firmware
Tracked-On: OAM-112144

Add ACRN hypervisor support

---

core/definitions.mk

this will happen only when the mixin of tee is set as "optee"
Tracked-On: OAM-112796

pack optee prebuilt binary into bootloader

---

core/definitions.mk
create_gpt_image.py

Create boot container separately for boot from multiple containers in SBL. This is controlled by "sbl_multicontainer" option.
Tracked-On: OAM-112552

Build separate boot containers for SBL

---

core/definitions.mk

Use debug version of optee in userdebug build

---

core/definitions.mk

Build a separate container file sbl_mod_tee for booting from multiple partitions feature.
Tracked-On: OAM-113549

Build separate container file for TEE

---

tasks/flashfiles.mk

Enable provision to compile vm1-2 and vm3 separately

---

tasks/flashfiles.mk
tasks/publish.mk

build qcow2 image if enabled
Tracked-On: OAM-118515

build qcow2 image if enabled

---

tasks/flashfiles.mk

This target will be used for Automotive related activities
Test done : Boot check done
Tracked-On: OAM-121402

New Target aaos_iasw is created

---

tasks/publish.mk

Add kernel debug files to publish maketarget for debug purpose

---

bootloader_from_zip
create_gpt_image.py
generate_factory_images
releasetools/bootloader_from_target_files
releasetools/flash_cmd_generator.py
releasetools/flashfiles_from_target_files
releasetools/intel_common.py
tasks/checkvendor.py

This reverts commit ead4c1f92fb83bf8e4393e3e0e1820f63bb395cf.
Reverting this patch since boot issue is seen on MBL Fab-B board.

Revert "Migrate python2 scripts to python3"

---

flash_scripts/android_flash_base_aaos.sh
flash_scripts/android_flash_vm1_2.sh
flash_scripts/android_flash_vm3.sh
flash_scripts/flash_vm1_2_rw.sh
flash_scripts/flash_vm3_rw.sh

The scripts are used to flash Android VM in SOS
Test Done:
flash android and boot
Tracked-On: OAM-123554

Add Android flash scripts

---

bootloader_from_zip
create_gpt_image.py
generate_factory_images
releasetools/bootloader_from_target_files
releasetools/flash_cmd_generator.py
releasetools/flashfiles_from_target_files
releasetools/intel_common.py
tasks/checkvendor.py

Tests Done: Boot check
Tracked-On: OAM

Migrate python2 scripts to python3

---

releasetools/flashfiles_from_target_files.sh

super.img in installer.cmd should not be change
Tracked-On: OAM-126572

Fix install to bare metal failure for tar.gz image

---

tasks/flashfiles.mk

Publish signed target_file image in below build command make flashfiles dist publish RELEASE_BUILD=true -j120 Test Done:
Boot
Tracked-On: OAM-131187

Add signed target_file image to publish directory

---

tasks/flashfiles.mk

Use apex pubkey instead of well known pubkey.
Tracked-On: OAM-131705

Change well known pubkey

---

tasks/flashfiles.mk

Add apk list and replace default certificates with apex certificate.
Tracked-On: OAM-131001

Replace default certificates by apk list
