projectceladon/device-intel-build

- releasetools/sign_target_files_efis
If allowZip64 is False, there will be exception for large files more than 4GB.
Exception: zipfile.LargeZipFile: Zipfile size would require ZIP64 extensions.
Jira: None.
Test: Test it on KBL-NUC.
Signed-off-by: Zhou, Lihua <lihuax.zhou@intel.com>
> Allow to process large zipfile as zip64 format

- create_gpt_image.py
The full disk image can be used as a USB live boot image, or Simulate
disk image.
Jira: https://01.org/jira/browse/CEL-13
Test: Test it in KBL NUC.
The original author is Perrot, ThomasX <thomasx.perrot@intel.com>.
Signed-off-by: Perrot, ThomasX <thomasx.perrot@intel.com>
Signed-off-by: Claude Brouat <claude.brouat@intel.com>
Signed-off-by: Leo Sartre <leox.sartre@intel.com>
Signed-off-by: Charles Johnson <charles.f.johnson@intel.com>
Signed-off-by: Jeremy Compostella <jeremy.compostella@intel.com>
Signed-off-by: roger feng <roger.feng@intel.com>
Signed-off-by: Benoit Fradin <benoit.fradin@intel.com>
Signed-off-by: geoffroy.weisenhorn <weisenhorn.geoffroy@intel.com>
Signed-off-by: gaohuadx <huadongx.gao@intel.com>
Signed-off-by: gli41 <genshen.li@intel.com>
Signed-off-by: kwen …
> Add the create_gpy_image.py. It is used to create a full disk image.

- releasetools/sign_target_files_efis
- test/ota-test-prepare
Test:
- resign cel_apl image: OK
- flash resigned cel_apl image on KBL NUC: OK
- OTA update with resign files: OK
- check that OTA update fails with not resigned OTA: OK
Tracked-On: OAM-71092
Signed-off-by: Regnier, Philippe <philippe.regnier@intel.com>
> ota: enable avb in resign scripts

- releasetools/sign_target_files_efis
- test/ota-test-prepare
kernelflinger.efi is added to vendor partition after resigning.
Partitions are now resigned after bootloader is signed and copied
to vendor directory in target file.
Test:
Boot to UI with resigned binaries
Boot to UI after OTA update with resigned binaries
Tracked-On: OAM-71983
Signed-off-by: phireg <philippe.regnier@intel.com>
> ota: fix ota after resign

- core/definitions.mk
It requires stack-protector, stack execution protection,
data relocation and protection (RELRO)
Add CFLAGS: -fstack-protector-strong -Wformat -Wformat-security -D_FORTIFY_SOURCE=2
Add LDFLAGS: -znoexecstack -zrelro -znow
Change-Id: I3c56445f0bb1c223460048d682bfe03882f17f3a
Tracked-On: OAM-73605
Signed-off-by: Heng Luo <heng.luo@intel.com>
> [PORT FROM PMRI] Add stack protection flag for kernelflinger

- releasetools/sign_target_files_efis
Target files can be > 4 GB.
Resign scripts must support it.
Tracked-On: OAM-86512
Signed-off-by: phireg <philippe.regnier@intel.com>
> ota: add support for zip files > 4GB

- tasks/resign.mk
- test/ota-test-prepare
When called through build command, the new build target
publish_resign allows build system to automatically resign
current binaries and copy them in publish directory.
In case of failure of resign operation, other build
operations are not blocked and will perform normally.
Tracked-On: OAM-86894
Signed-off-by: phireg <philippe.regnier@intel.com>
> ota: add build target publish_resign

- tasks/flashfiles.mk
- tasks/publish.mk
prebuilts tar has been enabled as part of enabling
setup path restrictions for Android 11. However
tar in prebuilts does not support --checkpoint option.
So using tar from host
Tracked-On: OAM-95316
Signed-off-by: yaravapa <yasoda.aravapalli@intel.com>
> Use host tar tool instead of tar from prebuilts

- tasks/flashfiles.mk
1. Apex files cannot be resigned successfully due
to the restriction of PATH tools, So append
SOONG_HOST_OUT to the PATH for sign_target_files_apks
command.
2. Create a release build for the GPT image from
a flashfiles release package.
Tracked-On: OAM-100099
Signed-off-by: ji, zhenlong z <zhenlong.z.ji@intel.com>
Signed-off-by: svenate <salini.venate@intel.com>
> Fix Release Candidate Build issue

- tasks/flashfiles.mk
- tasks/publish.mk
Remove caas.img/caas.img.gz from the CIV build and create new make command for Users in need.
Right now each and every build generates caas.img as part of build
process and it is uploaded to artifactory, consuming space and
processing time. Since not all users need it, we can allow it to
be created only as part of additional make commands that user
can pass while running an engineering build. This should improve
build time in CI and friendly to developer.
Developer can use "make publish_gptimage" to generate caas.img.gz
Tracked-On: OAM-102849
> Gptimage will not be built by default

- tasks/flashfiles.mk
Removed not supported caas_cfc and caas_dev targets.
Tracked-On: OAM-105021
Signed-off-by: Jeevaka Prabu Badrappan <jeevaka.badrappan@intel.com>
> Update valid build targets

- tasks/publish.mk
fb4sbl feature is not ready yet, remove to make "dist publish" build pass
Tracked-On: OAM-111199
> Remove fb4sbl image from publish target

- core/definitions.mk
These patches was added during 14 bring-up and was initially put in vendor-intel-utils. Moving it to corresponding repo as a part of clean-up.
Tracked-On: OAM-112683
> Updating the clang version to 17.0.2

- core/definitions.mk
Commit c5850ed5e07e ("Build separate boot containers for SBL") conflicts with 747a651af1c7 ("pack optee prebuilt binary into bootloader"), causing build failure when "tee" is enabled in mixins.spec.
Tracked-On: OAM-113156
> Fix build failure when tee is enabled

- core/definitions.mk
> Use optee-enabled ACRN binary for optee-enabled build

- core/definitions.mk
OPTEE_ELF is changed to optee binary built in Android.
Tracked-On: OAM-114532
> Change the source of OPTEE_ELF

- releasetools/bootloader_from_target_files
- releasetools/flashfiles_from_target_files.sh
- tasks/flashfiles.mk
Currently FFTF python script is used for creating flashfiles.zip. It uses ZipWrite python api which is time consuming and adds overhead to build time. Say, flash.json generation, unpacking of target files, installer.cmd generation, etc.
This fix helps to optimize build time and involves below changes:
- Use tar + pigz combo for faster flashfiles generation.
- Make FFTF a bash script as python doesn't directly support tar + pigz
- Add use_tar=true flag to "make flashfiles" to enable it. e,g, "make flashfiles -j<N> use_tar=true"
- The new script still supports all old functionalities, say, generation of installer.cmd, flash.json, repacking of bootloader.img, etc.
Tracked-On: OAM-112083
> Improve compilation speed for android build

- tasks/publish.mk
kernelflinger binary (kf4sbl.sbl) may be used as the bootloader of Android VM. Add it to pub directory of both publish_ci and publish maketarget so that it will be uploaded to artifactory.
Tracked-On: OAM-115247
> Add kernelflinger binary to publish_ci/publish maketarget

- releasetools/flashfiles_from_target_files.sh
- tasks/flashfiles.mk
directory is not required in final release packages
Test done:
make flashfiles use_tar=true
uzip flashfile.tar.gz and iso.tar.gz, no
directory in extracted files
Tracked-On: OAM-115250
> Remove directory while compressing android images

- releasetools/flashfiles_from_target_files.sh
gpt.ini is used to flash android images, add it to flashfiles to optimize the flash steps
Test done:
make flashfiles
make flashfiles use_tar=true
Tracked-On: OAM-115800
> Add gpt.ini to flashfiles

- releasetools/flashfiles_from_target_files.sh
create_gpt_image.py and gpt_ini2bin.py are used to flash android images, add them to flashfiles to
optimize the flash steps
Test done:
make flashfiles
make flashfiles use_tar=true
Tracked-On: OAM-116719
> build: Add flash scripts to flashfiles.tar.gz

- tasks/flashfiles.mk
epolicy_freeze_test compares the plat sepolicy with the prebuilt sepolicy, build will fail if there are diffs.
check-vintf-all is used to check the compatibility between framework and vendor.
Test done: sepolicy freeze test and vintf check will be executed during make flashfiles.
Tracked-On: OAM-121993
> Add sepolicy_freeze_test module to flashfiles target

- releasetools/flashfiles_from_target_files.sh
- tasks/flashfiles.mk
release key is used for release images
Test Done:
build and boot success
make flashfiles -j20
make flashfiles -j20 iso_image=false use_tar=true
make flashfiles -j20 RELEASE_BUILD=true
make flashfiles -j00 iso_image=false use_tar=true
RELEASE_BUILD=true
make flashfiles -j20 publish_gptimage RELEASE_BUILD=true
iso_image=false use_tar=true
Tracked-On: OAM-124136
> Support release build for tar.gz images

- bootloader_from_zip
- create_gpt_image.py
- generate_factory_images
- releasetools/bootloader_from_target_files
- releasetools/flash_cmd_generator.py
- releasetools/flashfiles_from_target_files
- releasetools/intel_common.py
- tasks/checkvendor.py
Tests Done: Boot check on civ and base_aaos
Tracked-On: OAM-
> Migrate python2 scripts to python3

- releasetools/flashfiles_from_target_files.sh
The gpt.ini file is a GPT configuration file used
during the Android flashing process in the SOS environment. Each build may have different partition tables.
We need these GPT files to prevent flashing failures
Test Done:
make flashfiles use_tar=true
Flash and boot success
Tracked-On: OAM-124426
> Add gpt.ini to flashfiles images

- tasks/flashfiles.mk
This patch will add target_variant and hostname in the generated flashfiles so that it is easier to track at a later stage.
Tests Done: Build and check file names
Tracked-On: OAM-125328
> Update TARGET VARIANT and HOSTNAME in file name

- releasetools/flashfiles_from_target_files.sh
These partition tables will be used in android flash if android image is devided into read-only image
and read-write image
Test Done:
make flashfiles to generate gpt_ro.bin gpt_rw.bin
and gpt_rw_nolic.bin
Flash these gpt tables to device through fastboot
and boot success
Tracked-On: OAM-124748
> Separate GPT table as read-only and read-write

- testkeys/cts-release-test/Android.bp
The cts release test key will be used to widewive apex because there's key issues when running cts CtsSecurityTestCases android.security.cts.PackageSignatureTest#testPackageSignatures
Test Done:
1. run cts CtsSecurityTestCases
Tracked-On: OAM-125207
> Define the cts-release-test key path.

- tasks/flashfiles.mk
selinux_policy will introduce more sepolicy compliant tests for flashfiles build which is important for the sepolicy rules development.
Tracked-On: OAM-128247
> Introduce more sepolicy treble compliant test for flashfiles build

- tasks/flashfiles.mk
selinux_policy will introduce more sepolicy test which is important for the sepolicy rules development.
Tracked-On: OAM-128246
> Include more sepolicy test in flashfiles build

- core/definitions.mk
This patch will update the clang patch to 19 as
we are moving to latest clang with A15 tag r9 update.
Tests Done: Build and boot
Tracked-On: OAM-128386
> Updating the clang path according to new clang lib

- tasks/flashfiles.mk
This is required to pass the MctsAppSecurityHostTestCases android.appsecurity.cts.ApexSignatureVerificationTest#testApexPubKeyIsNotWellKnownKey test case.
Tracked-On: OAM-127925
> Add more apex packages to the resign apex list

- tasks/flashfiles.mk
Used to fix the following cts failure;
android.appsecurity.cts.ApexSignatureVerificationTest# testApexPubKeyIsNotWellKnownKey
Tracked-On: OAM-131008
> Add four extra apex packages to resign list

- tasks/publish.mk
The files are linux symbols used for kernel debug
Test Done:
Build pass
Tracked-On: OAM-132017
> publish vmlinux and system map for system debug
